apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: uumd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uumd
    app.kubernetes.io/part-of: byoc-app-hlvi
  name: uumdyse0
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: uumd
    weight: null
status: {}
